services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ml_network

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ml_network
    environment:
      - BACKEND_API_URL=${BACKEND_API_URL}

networks:
  ml_network:
    driver: bridge