services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    networks:
      - ml_network
    environment:
      - REACT_APP_API_URL=http://backend:8000

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    networks:
      - ml_network
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}

networks:
  ml_network:
    driver: bridge